language: python
addons:
  apt:
    packages:
    - wget
env:
    - TOX_ENV=py27
#    - TOX_ENV=py32
# Disabling py32 tests until the following issue is fixed:
# pip 8.x breaks python 3.2 compatibility
# https://github.com/pypa/pip/issues/3390
#    - TOX_ENV=py33
# pandas 0.19.x breaks python 3.3 compatibility
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=pypy3
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=coverage
install:
    - pip install tox
    - pip install coveralls
    - mkdir influxdb_install
    - wget https://dl.influxdata.com/influxdb/releases/influxdb_0.13.0_amd64.deb
    - dpkg -x influxdb*.deb influxdb_install
script:
    - export INFLUXDB_PYTHON_INFLUXD_PATH=$(pwd)/influxdb_install/usr/bin/influxd
    - travis_wait 30 tox -e $TOX_ENV
after_success:
    - if [ "$TOX_ENV" == "coverage" ] ; then coveralls; fi
notifications:
    email: false

sudo: false

# Travis caching
cache: false
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
