language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"

env:
  - INFLUXDB_VER=1.2.4
#  - INFLUXDB_VER=1.3.9
#  - INFLUXDB_VER=1.4.2
#  - INFLUXDB_VER=1.5.4

addons:
  apt:
    packages:
    - wget

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pep257
    - python: 3.6
      env: TOX_ENV=docs
    - python: 3.6
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=coverage

install:
    - pip install tox-travis
    - pip install setuptools==20.6.6
    - pip install coveralls
    - mkdir -p "influxdb_install/${INFLUXDB_VER}"
    - if [ -n "${INFLUXDB_VER}" ] ; then wget "https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB_VER}_amd64.deb" ; fi
    - if [ -n "${INFLUXDB_VER}" ] ; then dpkg -x influxdb*.deb "influxdb_install/${INFLUXDB_VER}" ; fi

script:
    - export "INFLUXDB_PYTHON_INFLUXD_PATH=$(pwd)/influxdb_install/${INFLUXDB_VER}/usr/bin/influxd"
    - if [ -n "${TOX_ENV}" ]; then tox -e "${TOX_ENV}"; else tox; fi

after_success:
    - if [ "${TOX_ENV}" == "coverage" ] ; then coveralls; fi

notifications:
    email: false

sudo: false

# Travis caching
cache: false
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
