language: python

addons:
  apt:
    packages:
    - wget

matrix:
  allow_failures:
    - python: 3.4
      env: TOX_ENV=docs
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: pypy-5.3.1
      env: TOX_ENV=pypy
    - python: 3.4
      env: TOX_ENV=py34
# An issue in travis-ci prevents this case from running
# Link to issue: https://github.com/travis-ci/travis-ci/issues/6304
#    - python: pypy3.3-5.2-alpha1
#      env: TOX_ENV=pypy3
    - python: 3.4
      env: TOX_ENV=docs
    - python: 3.4
      env: TOX_ENV=flake8
    - python: 3.4
      env: TOX_ENV=coverage

install:
    - pip install tox
    - pip install coveralls
    - mkdir influxdb_install
    - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.1.0_amd64.deb
    - dpkg -x influxdb*.deb influxdb_install
script:
    - export INFLUXDB_PYTHON_INFLUXD_PATH=$(pwd)/influxdb_install/usr/bin/influxd
    - tox -e $TOX_ENV
after_success:
    - if [ "$TOX_ENV" == "coverage" ] ; then coveralls; fi
notifications:
    email: false

sudo: false

# Travis caching
cache: false
#  directories:
#    - $HOME/.cache/pip
#before_cache:
#  - rm -f $HOME/.cache/pip/log/debug.log
